spring:
  datasource:
    url: jdbc:mysql://192.168.47.130:3306/springboot-easypoi
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  main:
    allow-bean-definition-overriding: true
#user_name-->userName
mybatis:
  configuration:
    map-underscore-to-camel-case: true